
FROM node:10

RUN mkdir -p /usr/src/app/ 

WORKDIR /usr/src/app

COPY package.json /usr/src/app

# RUN npm install

ENV GOOGLE_APPLICATION_CREDENTIALS="/.gcp/storage.json"

COPY . /usr/src/app

CMD [ "npm", "start" ]